server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://192.168.178.61:3306/tasty_role
    username: root
    password: EFv9C6Kq0gMdmoaA
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  jwtSecret: 843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3
  jwtExpirationTime: 86400000